export const languages = [
    { "value": "BLANK_1427118194589", "label": "" },
    { "value": "allemand__german_", "label": "Allemand (German)" },
    { "value": "anglais__english_", "label": "Anglais (English)" },
    { "value": "arabe__arabic_", "label": "Arabe (Arabic)" },
    { "value": "chinois__simplified_chinese_", "label": "Chinois (Simplified Chinese)" },
    { "value": "cor_en__korean_", "label": "Coréen (Korean)" },
    { "value": "danois__danish_", "label": "Danois (Danish)" },
    { "value": "espagnol__spanish_", "label": "Espagnol (Spanish)" },
    { "value": "finnois__finnish_", "label": "Finnois (Finnish)" },
    { "value": "fran_ais__french_", "label": "Français (French)" },
    { "value": "grec__greek_", "label": "Grec (Greek)" },
    { "value": "h_breu__hebrew_", "label": "Hébreu (Hebrew)" },
    { "value": "italien__italian_", "label": "Italien (Italian)" },
    { "value": "japonais__japanese_", "label": "Japonais (Japanese)" },
    { "value": "n_erlandais__dutch_", "label": "Néerlandais (Dutch)" },
    { "value": "norv_gien__norwegian_", "label": "Norvégien (Norwegian)" },
    { "value": "portugais__portuguese_", "label": "Portugais (Portuguese)" },
    { "value": "russe__russian_", "label": "Russe (Russian)" },
    { "value": "su_dois__swedish_", "label": "Suédois (Swedish)" },
    { "value": "turc__turkish_", "label": "Turc (Turkish)" }
]
