export const  talentOptions = [
    {"value": "account_executive", "label": "Account Executive"},
    {"value": "account_director__cr_a_", "label": "Account Director (Créa)"},
    {"value": "account_director__media_", "label": "Account Director (Media)"},
    {"value": "animateur_2d_3d", "label": "Animateur 2D/3D"},
    {"value": "attach__e__de_presse", "label": "Attaché(e) de presse"},
    {"value": "brand_strategist", "label": "Brand strategist"},
    {"value": "charg__e__de_communication", "label": "Chargé(e) de communication"},
    {"value": "chef_de_projet", "label": "Chef de projet"},
    {"value": "chef_fe__de_marque", "label": "Chef(fe) de marque"},
    {"value": "chef_fe__de_produit", "label": "Chef(fe) de produit"},
    {"value": "chef_fe__de_publicit_", "label": "Chef(fe) de publicité"},
    {"value": "community_manager", "label": "Community Manager"},
    {"value": "concepteur_r_dacteur", "label": "Concepteur-rédacteur"},
    {"value": "consultant_crm", "label": "Consultant CRM"},
    {"value": "consultant_marketing", "label": "Consultant Marketing"},
    {"value": "consultant_sea", "label": "Consultant SEA"},
    {"value": "consultant_e__en_communication", "label": "Consultant(e) en communication"},
    {"value": "consultant_e__en_m_dias", "label": "Consultant(e) en médias"},
    {"value": "copywriter", "label": "Copywriter"},
    {"value": "data_analyst", "label": "Data analyst"},
    {"value": "designer_ux_ui__exp_rience_utilisateur___interface_utilisateur_", "label": "Designer UX/UI (Expérience utilisateur / Interface utilisateur)"},
    {"value": "digital_marketing_specialist", "label": "Digital marketing specialist"},
    {"value": "directeur_artistique___graphiste", "label": "Directeur artistique / Graphiste"},
    {"value": "directeur_trice__marketing", "label": "Directeur(trice) marketing"},
    {"value": "illustrateur", "label": "Illustrateur"},
    {"value": "influenceur", "label": "Influenceur"},
    {"value": "infographiste", "label": "Infographiste"},
    {"value": "media_buyer", "label": "Media Buyer"},
    {"value": "media_planner", "label": "Media Planner"},
    {"value": "media_trader", "label": "Media Trader"},
    {"value": "monteur_vid_o", "label": "Monteur vidéo"},
    {"value": "motion_designer", "label": "Motion designer"},
    {"value": "photographe", "label": "Photographe"},
    {"value": "podcaster", "label": "Podcaster"},
    {"value": "product_owner", "label": "Product Owner"},
    {"value": "r_alisat_eur__rice_", "label": "Réalisat-eur(-rice)"},
    {"value": "responsable_des__tudes_de_march_", "label": "Responsable des études de marché"},
    {"value": "responsable_des_relations_publiques", "label": "Responsable des relations publiques"},
    {"value": "responsable_marketing_op_rationnel", "label": "Responsable marketing opérationnel"},
    {"value": "responsable_marketing_produit", "label": "Responsable marketing produit"},
    {"value": "social_media_strategist", "label": "Social Media Strategist"},
    {"value": "sp_cialiste_en_r_f_rencement__seo_", "label": "Spécialiste en référencement (SEO)"},
    {"value": "traffic_manager__agence_cr_ative_", "label": "Traffic Manager (Agence Créative)"},
    {"value": "traffic_manager__m_dia_", "label": "Traffic Manager (Média)"}
]
